---
function:
  name: omni-bio-rad-create-shipment-${self:provider.stage}
  handler: src/create-shipment/index.handler
  runtime: nodejs20.x
  timeout: 30
  layers:
    - { Ref: NodeModulesLambdaLayer }
  package:
    include:
      - 'src/create-shipment/**'
    exclude:
      - '**/*'
  events:
    - http:
        path: /LbnFreightOrderForSubcontracting
        method: POST
