---
function:
  name: omni-bio-rad-create-shipment-${self:provider.stage}
  handler: src/create-shipment/index.handler
  runtime: nodejs20.x
  timeout: 30
  layers:
    - { Ref: NodeModulesLambdaLayer }
  package:
    patterns:
      - '!**/*'
      - src/create-shipment/**
      - src/Shared/**
  events:
    - http:
        path: /LbnFreightOrderForSubcontracting
        method: POST
        private: true
  environment:
    WT_URL: ${ssm:/omni-dw/${self:provider.stage}/createShipment/wt/url} #TO BE CREATED THROUGH TERRAFORM BIO RAD REPO
    UPLOAD_DOCUMENT_API: ${ssm:/omni-dw/${self:provider.stage}/api/addDocument}
    # WEBSLI_GET_DOC_URL: ${ssm:/omni-dw/${self:provider.stage}/websli/api/base.url}  #TO BE CREATED THROUGH TERRAFORM BIO RAD REPO
    # WEBSLI_KEY: ${ssm:/omni-dw/${self:provider.stage}/get-document/websli-key.default}
