---
function:
  name: omni-bio-rad-create-shipment-${self:provider.stage}
  handler: src/create-shipment/index.handler
  runtime: nodejs20.x
  timeout: 30
  layers:
    - { Ref: NodeModulesLambdaLayer }
  package:
    include:
      - 'src/create-shipment/**'
    exclude:
      - '**/*'
  events:
    - http:
        path: /LbnFreightOrderForSubcontracting
        method: POST
        private: true
  environment:
    WT_URL: ${ssm:/omni-dw/${self:provider.stage}/createShipment/wt/url}
    DB_USERNAME: ${ssm:/omni-dw/${self:provider.stage}/worldTrak/source-db/userName}
    DB_PASSWORD: ${ssm:/omni-dw/${self:provider.stage}/worldTrak/source-db/password}
    DB_SERVER: ${ssm:/omni-dw/${self:provider.stage}/worldTrak/source-db/serverName}
    DB_PORT: ${ssm:/omni-dw/${self:provider.stage}/worldTrak/source-db/port}
    DB_DATABASE: ${ssm:/omni-dw/${self:provider.stage}/worldTrak/source-db/name}
