---
function:
  name: omni-bio-rad-create-shipment-${self:provider.stage}
  handler: src/create-shipment/index.handler
  runtime: nodejs20.x
  timeout: 30
  layers:
    - { Ref: NodeModulesLambdaLayer }
  package:
    patterns:
      - '!**/*'
      - src/create-shipment/**
      - src/Shared/**
  events:
    - http:
        path: /LbnFreightOrderForSubcontracting
        method: POST
        private: true
  environment:
    WT_URL: ${ssm:/omni/${self:provider.stage}/bio-rad/wt/create-shipment/api.url}
    UPLOAD_DOCUMENT_API: ${ssm:/omni/${self:provider.stage}/bio-rad/wt/add-document/api.url}
    LBN_TOKEN_URL: ${ssm:/omni/${self:provider.stage}/bio-rad/lbn-token-endpoint}
    LBN_TOKEN_CLIENT_ID: ${ssm:/omni/${self:provider.stage}/bio-rad/lbn-token-endpoint/client-id}
    LBN_TOKEN_CLIENT_SECRET: ${ssm:/omni/${self:provider.stage}/bio-rad/lbn-token-endpoint/client-secret}
    LBN_SEND_URL: ${ssm:/omni/${self:provider.stage}/bio-rad/lbn-send-endpoint}
