---
function:
  name: omni-bio-rad-send-order-events-${self:provider.stage}
  handler: src/send-order-events/index.handler
  runtime: nodejs20.x
  timeout: 900
  layers:
    - { Ref: NodeModulesLambdaLayer }
  package:
    patterns:
      - '!**/*'
      - src/send-order-events/**
      - src/Shared/**
  events:
    - sqs:
        arn: ${ssm:/omni/${self:provider.stage}/bio-rad/send-order-events/sqs.arn}
        batchSize: 10
  environment:
    SHIPMENT_HEADER_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-header/ddb.tableName}
