---
function:
  name: omni-bio-rad-update-shipment-processor-${self:provider.stage}
  handler: src/update-shipment-processor/index.handler
  runtime: nodejs20.x
  timeout: 900
  layers:
    - { Ref: NodeModulesLambdaLayer }
  package:
    patterns:
      - '!**/*'
      - src/update-shipment-processor/**
      - src/Shared/**
  events:
    - stream:
        arn: ${ssm:/omni/${self:provider.stage}/bio-rad/ddb.streamArn}
        batchSize: 1
        maximumRetryAttempts: 2
        bisectBatchOnFunctionError: true
        filterPatterns:
          - { dynamodb: { NewImage: { Process: { S: ['UPDATE'] }, Status: { S: ['PENDING'] } } } }
  environment:
    WT_URL: ${ssm:/omni/${self:provider.stage}/bio-rad/wt/create-shipment/api.url}
    UPDATE_SOURCE_DB_URL: ${ssm:/omni/${self:provider.stage}/bio-rad/update-source-db-endpoint}
    UPDATE_SOURCE_DB_API_KEY: ${ssm:/omni/${self:provider.stage}/bio-rad/api-key}
    LBN_SEND_URL: ${ssm:/omni/${self:provider.stage}/bio-rad/lbn-send-endpoint}
    LBN_TOKEN_URL: ${ssm:/omni/${self:provider.stage}/bio-rad/lbn-token-endpoint}
    LBN_TOKEN_USERNAME: ${ssm:/omni/${self:provider.stage}/bio-rad/lbn-token-endpoint/username}
    LBN_TOKEN_PASSWORD: ${ssm:/omni/${self:provider.stage}/bio-rad/lbn-token-endpoint/password}
    CANCEL_SHIPMENT_URL: ${ssm:/omni/${self:provider.stage}/bio-rad/wt/add-document/api.url}
    GET_DOCUMENT_URL: ${ssm:/omni/${self:provider.stage}/bio-rad/wt/get-document/api.url}
    LBN_TOKEN_AUTHORIZATION: ${ssm:/omni/${self:provider.stage}/bio-rad/lbn-token-endpoint/authorization}